### ISSUE TITLE
The grammatical information in the Arabic dictionary is too much

### ISSUE THREAD

**Issue by YossefGamerr** [yomidevs/kaikki-to-yomitan#44]
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/169157659/70bc2e85-06a3-4e0d-bafe-992bbf27ab04)

some information here is pretty much useless, how do I manually remove it

**Comment by StefanVukovic99** [comment]
If you turn on Advanced settings, the last settings in the "Appearance" section is "Configure custom CSS". Put this there:
```css
ul.inflection-rule-chains {
    display: none;
}
```
(You already had issue #41 open about this. Please close them both if this fixes your problem)

**Comment by YossefGamerr** [comment]
> If you turn on Advanced settings, the last setting in the "Appearance" section is "Configure custom CSS". Put this there:
> 
> ```css
> ul.inflection-rule-chains {
>     display: none;
> }
> ```
> 
> (You already had issue #41 open about this. Please close them both if this fixes your problem)


But this removes all of it, whereas some information is valuable but some are useless. So is there no way to pick certain info and block others?

**Comment by Kuuuube** [comment]
Here is an example showing only the first two items:

```css
li.inflection-rule-chain {
    display: none;
}

li.inflection-rule-chain:nth-child(1),
li.inflection-rule-chain:nth-child(2) {
    display: block;
}
```

If you want more or less items to show it should be obvious enough how to get that. Beyond this it isn't possible to parse the data and pick out specific info that you deem important.
